// This file is generated by GoAdmin CLI adm.
package tables

import "github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"

// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "api_case" => http://localhost:9033/admin/info/api_case
// "api_sum_up" => http://localhost:9033/admin/info/api_sum_up
// "api_test_detail" => http://localhost:9033/admin/info/api_test_detail
// "api_test_result" => http://localhost:9033/admin/info/api_test_result
// "case_test_count" => http://localhost:9033/admin/info/case_test_count
// "common_variable" => http://localhost:9033/admin/info/common_variable
// "host" => http://localhost:9033/admin/info/host
// "issue" => http://localhost:9033/admin/info/issue
// "issue_milestone_count" => http://localhost:9033/admin/info/issue_milestone_count
// "issue_tag_count" => http://localhost:9033/admin/info/issue_tag_count
// "product_gitlab" => http://localhost:9033/admin/info/product_gitlab
// "test_case" => http://localhost:9033/admin/info/test_case
// "test_progress_schedule" => http://localhost:9033/admin/info/test_progress_schedule
// "api_detail" => http://localhost:9033/admin/info/api_detail
// "api_test_data" => http://localhost:9033/admin/info/api_test_data
//
// example end
//
var Generators = map[string]table.Generator{

	"api_case":               GetApiCaseTable,
	"api_sum_up":             GetApiSumUpTable,
	"api_test_detail":        GetApiTestDetailTable,
	"api_test_result":        GetApiTestResultTable,
	"case_test_count":        GetCaseTestCountTable,
	"common_variable":        GetCommonVariableTable,
	"host":                   GetHostTable,
	"issue":                  GetIssueTable,
	"issue_milestone_count":  GetIssueMilestoneCountTable,
	"issue_tag_count":        GetIssueTagCountTable,
	"product_gitlab":         GetProductGitlabTable,
	"test_case":              GetTestCaseTable,
	"test_progress_schedule": GetTestProgressScheduleTable,
	"api_detail":             GetApiDetailTable,
	"api_test_data":          GetApiTestDataTable,

	// generators end
}
